# QNet-NO Main Coordinator Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qnet-no-coordinator
  namespace: qnet-no
  labels:
    app: qnet-no
    component: coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qnet-no
      component: coordinator
  template:
    metadata:
      labels:
        app: qnet-no
        component: coordinator
    spec:
      containers:
      - name: qnet-no-coordinator
        image: qnet-no:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: api
        - containerPort: 8080
          name: web
        envFrom:
        - configMapRef:
            name: qnet-no-config
        - secretRef:
            name: qnet-no-secret
        env:
        - name: QNET_NODE_ID
          value: "0"
        - name: QNET_ROLE
          value: "coordinator"
        resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
            nvidia.com/gpu: 1
          limits:
            memory: "8Gi"
            cpu: "4000m"
            nvidia.com/gpu: 1
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: cache
          mountPath: /app/cache
        - name: models
          mountPath: /app/models
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: qnet-no-logs-pvc
      - name: cache
        persistentVolumeClaim:
          claimName: qnet-no-cache-pvc
      - name: models
        persistentVolumeClaim:
          claimName: qnet-no-models-pvc
      nodeSelector:
        nvidia.com/gpu.present: "true"
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule

---
# QNet-NO Worker Deployment (Auto-scaling)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qnet-no-worker
  namespace: qnet-no
  labels:
    app: qnet-no
    component: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qnet-no
      component: worker
  template:
    metadata:
      labels:
        app: qnet-no
        component: worker
    spec:
      containers:
      - name: qnet-no-worker
        image: qnet-no:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: api
        envFrom:
        - configMapRef:
            name: qnet-no-config
        - secretRef:
            name: qnet-no-secret
        env:
        - name: QNET_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: QNET_ROLE
          value: "worker"
        - name: QNET_COORDINATOR_HOST
          value: "qnet-no-coordinator-service"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
            nvidia.com/gpu: 1
          limits:
            memory: "4Gi"
            cpu: "2000m"
            nvidia.com/gpu: 1
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: cache
          mountPath: /app/cache
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: qnet-no-logs-pvc
      - name: cache
        persistentVolumeClaim:
          claimName: qnet-no-cache-pvc
      nodeSelector:
        nvidia.com/gpu.present: "true"
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule