# Persistent Volume Claims for QNet-NO
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qnet-no-logs-pvc
  namespace: qnet-no
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qnet-no-cache-pvc
  namespace: qnet-no
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qnet-no-models-pvc
  namespace: qnet-no
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qnet-no-data-pvc
  namespace: qnet-no
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: standard